In [4]:
import sys
print(sys.executable)

c:\Users\suzan\OneDrive\Documents\Work Projects\Generating_Questions\.venv\Scripts\python.exe

In [23]:
from bertopic import BERTopic
import pandas as pd
from umap import UMAP

In [3]:
with open("questions.txt", "r", encoding="utf-8") as f:
    sentences = f.read().splitlines()

len(sentences)

832

In [25]:
from sentence_transformers import SentenceTransformer

sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
#Reduce high dimensions
umap_model = UMAP(n_neighbors=20, n_components=5, min_dist=0.0, metric="cosine")
hdbscan_model = HDBSCAN(
    min_cluster_size=5,
    min_samples=1,
    metric="euclidean",
    cluster_selection_method="eom"
)

topic_model = BERTopic(
    embedding_model=sentence_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    nr_topics="auto"
)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 434.43it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

NameError: name 'HDBSCAN' is not defined

In [17]:
topics, probs = topic_model.fit_transform(sentences)

In [18]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,217,-1_my_to_it_is,"[my, to, it, is, when, for, should, or, life, ...","[﻿I don’t know what to do with my life, what a..."
1,0,77,0_forgive_someone_forgiveness_hurt,"[forgive, someone, forgiveness, hurt, myself, ...",[Should I forgive myself even if the people I ...
2,1,73,1_their_to_should_be,"[their, to, should, be, parents, ethical, is, ...",[Should someone be allowed to refuse life-savi...
3,2,63,2_relationship_marriage_is_in,"[relationship, marriage, is, in, partner, mora...",[Is it moral to prioritize my marriage over my...
4,3,54,3_it_is_to_if,"[it, is, to, if, tell, privacy, and, honesty, ...",[Is it okay to keep secrets from my partner if...
5,4,45,4_violence_ever_war_defense,"[violence, ever, war, defense, is, justified, ...","[Is self-defense always morally justified, eve..."
6,5,40,5_death_afterlife_after_beliefs,"[death, afterlife, after, beliefs, about, the,...",[Can someone live a fully moral life without a...
7,6,38,6_happiness_prioritize_own_my,"[happiness, prioritize, own, my, it, over, to,...",[Should we prioritize our own happiness over t...
8,7,32,7_meaning_life_purpose_faith,"[meaning, life, purpose, faith, suffering, doe...","[What is the purpose of life?, Does my religio..."
9,8,31,8_family_with_who_member,"[family, with, who, member, contact, to, my, c...",[Should I cut contact with a family member who...
10,9,30,9_guilt_guilty_feel_should,"[guilt, guilty, feel, should, about, or, somet...",[When does guilt about past decisions prevent ...
11,10,28,10_community_values_my_to,"[community, values, my, to, in, with, group, p...","[How do I balance ""fitting in"" with a communit..."
12,11,26,11_give_charity_wealth_money,"[give, charity, wealth, money, to, donate, wea...",[Is it morally okay to spend money on self-car...
13,12,25,12_environment_environmental_products_harm,"[environment, environmental, products, harm, h...",[Do I have a moral duty to care for the enviro...
14,13,19,13_control_self_does_religion,"[control, self, does, religion, require, or, m...",[Does religion view self-control as a virtue I...
15,14,18,14_addiction_my_with_an,"[addiction, my, with, an, deserves, drug, subs...",[How do I balance compassion for someone with ...
16,15,16,15_time_for_guilty_instead,"[time, for, guilty, instead, on, feel, tasks, ...",[Should I feel guilty for spending hours on so...

In [9]:
topic_model.get_topic(0)

[('life', np.float64(0.0752440882811972)),
 ('happiness', np.float64(0.07468121100712836)),
 ('meaning', np.float64(0.06941139122549415)),
 ('purpose', np.float64(0.0442339463132035)),
 ('suffering', np.float64(0.04255749661918283)),
 ('or', np.float64(0.042051907966030574)),
 ('does', np.float64(0.040737407977904434)),
 ('of', np.float64(0.037556228748173826)),
 ('is', np.float64(0.037516404839205694)),
 ('good', np.float64(0.03556248143196589))]

In [ ]:
topic_model.get_representative_docs(0)

["Is it morally required to forgive someone who has wronged you, even if they haven't apologized?",
 "Do I owe forgiveness to someone who hurt me if they've genuinely apologized and changed?",
 "Do I have to forgive someone who hurt me if they haven't apologized or changed?"]

In [16]:
topic_model.get_representative_docs(5)

["Is it ever okay to lie to protect someone's feelings, and if so, when does it cross a line?",
 'Is it okay to keep secrets from my partner if I believe the truth would cause unnecessary pain?',
 "Is it okay to tell a small lie to spare someone's feelings if the truth would cause unnecessary pain?"]

In [19]:
df_sentences = pd.DataFrame({"Topics": topics, "Question": sentences})
df_sentences.head(10)

   Topics                                           Question
0      -1  ﻿I don’t know what to do with my life, what ad...
1      -1  What is your process for making major life dec...
2       6  Do I have a moral obligation to take full resp...
3      -1  Is it wrong to rely on others to fix my proble...
4      13  According to religious teachings, am I account...
5      -1  Should I feel morally responsible for not usin...
6       6  Is it ethical to avoid personal growth because...
7      -1  Do I have a duty to set a good example for my ...
8      -1  Is blaming external factors (like society or f...
9      13  What does my religion say about free will and ...

In [ ]:
topic_model.visualize_topics()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'customdata': array([[0, 'forgive | someone | forgiveness | hurt | myself', 74],
                                   [1, 'their | to | should | be | parents', 73],
                                   [2, 'relationship | marriage | in | is | partner', 65],
                                   [3, 'violence | ever | defense | war | is', 46],
                                   [4, 'life | meaning | purpose | faith | suffering', 39],
                                   [5, 'death | afterlife | beliefs | after | about', 39],
                                   [6, 'tell | it | is | honesty | to', 38],
                                   [7, 'happiness | prioritize | happy | own | over', 31],
                                   [8, 'family | with | who | member | contact', 30],
                                   [9, 'guilt | guilty | feel | something | healthy', 29],
                                   [10, 'community | values | my | to | in', 29],
                                   [11, 'give | charity | wealth | money | to', 27],
                                   [12, 'environment | environmental | products | meat | harm', 25],
                                   [13, 'addiction | drinking | an | my | with', 19],
                                   [14, 'job | stay | stable | to | pursue', 15],
                                   [15, 'time | for | work | guilty | instead', 15],
                                   [16, 'control | self | religion | does | body', 14]], dtype=object),
              'hovertemplate': '<b>Topic %{customdata[0]}</b><br>%{customdata[1]}<br>Size: %{customdata[2]}',
              'legendgroup': '',
              'marker': {'color': '#B0BEC5',
                         'line': {'color': 'DarkSlateGrey', 'width': 2},
                         'size': {'bdata': 'SklBLicnJh8eHR0bGRMPDw4=', 'dtype': 'i1'},
                         'sizemode': 'area',
                         'sizeref': 0.04625,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': {'bdata': ('niWOQQiEuMD12HZB00XGwIYLt8Bjwr' ... 'VBPZGEQVYpkkHxfYJBgUuPQXY5t8A='),
                    'dtype': 'f4'},
              'xaxis': 'x',
              'y': {'bdata': ('lUhuQVXXwr8VUrVBnSXWv7i1JL+3Ao' ... 'FB+peuQf9eaEG52bNBn8NdQdvXUL4='),
                    'dtype': 'f4'},
              'yaxis': 'y'}],
    'layout': {'annotations': [{'showarrow': False,
                                'text': 'D1',
                                'x': np.float32(-7.1254272),
                                'y': np.float32(9.556833),
                                'yshift': 10},
                               {'showarrow': False,
                                'text': 'D2',
                                'x': np.float32(6.942642),
                                'xshift': 10,
                                'y': np.float32(26.06484)}],
               'height': 650,
               'hoverlabel': {'bgcolor': 'white', 'font': {'family': 'Rockwell', 'size': 16}},
               'legend': {'itemsizing': 'constant', 'tracegroupgap': 0},
               'margin': {'t': 60},
               'shapes': [{'line': {'color': '#CFD8DC', 'width': 2},
                           'type': 'line',
                           'x0': np.float32(6.942642),
                           'x1': np.float32(6.942642),
                           'y0': np.float32(-6.9511747),
                           'y1': np.float32(26.06484)},
                          {'line': {'color': '#9E9E9E', 'width': 2},
                           'type': 'line',
                           'x0': np.float32(-7.1254272),
                           'x1': np.float32(21.010712),
                           'y0': np.float32(9.556833),
                           'y1': np.float32(9.556833)}],
               'sliders': [{'active': 0,
                            'pad': {'t': 50},
                            'steps': [{'args': [{'marker.color': [['red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 0',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  'red', '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 1',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 2',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 3',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 4',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 5',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 6',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 7',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 8',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 9',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5']]}],
                                       'label': 'Topic 10',
                                       'method': 'update'},
                                      {'args': [{'marker.color': [['#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5',
                                                                  '#B0BEC5', 'red',

In [10]:
topic_model.visualize_barchart(top_n_topics=16)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'marker': {'color': '#D55E00'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.04255749661918283, 0.0442339463132035, 0.06941139122549415,
                    0.07468121100712836, 0.0752440882811972],
              'xaxis': 'x',
              'y': [suffering  , purpose  , meaning  , happiness  , life  ],
              'yaxis': 'y'},
             {'marker': {'color': '#0072B2'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.04860657823260553, 0.05472622386373563, 0.06130425489214048,
                    0.07060320544672809, 0.11564649995593422],
              'xaxis': 'x2',
              'y': [myself  , hurt  , forgiveness  , someone  , forgive  ],
              'yaxis': 'y2'},
             {'marker': {'color': '#CC79A7'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.041653344576407146, 0.04467898862286715, 0.0455380474120158,
                    0.046921769446869856, 0.050621539288411045],
              'xaxis': 'x3',
              'y': [ethical  , should  , be  , their  , to  ],
              'yaxis': 'y3'},
             {'marker': {'color': '#E69F00'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.04167424499238797, 0.04475665110797308,
                    0.045586656272386304, 0.06305297724919563, 0.07726561914613987],
              'xaxis': 'x4',
              'y': [partner  , in  , is  , marriage  , relationship  ],
              'yaxis': 'y4'},
             {'marker': {'color': '#56B4E9'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.04652217523631931, 0.04671095221147, 0.04671095221147,
                    0.04811878580894714, 0.06088280487793075],
              'xaxis': 'x5',
              'y': [is  , war  , defense  , ever  , violence  ],
              'yaxis': 'y5'},
             {'marker': {'color': '#009E73'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.04698358422826846, 0.049336384435008755,
                    0.055792494950051605, 0.05785888461934925, 0.06056641182581031],
              'xaxis': 'x6',
              'y': [honesty  , to  , is  , tell  , it  ],
              'yaxis': 'y6'},
             {'marker': {'color': '#F0E442'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.049429734739861904, 0.05360628376027466,
                    0.05688192718200396, 0.09340535075912006, 0.10573931413357306],
              'xaxis': 'x7',
              'y': [about  , beliefs  , after  , afterlife  , death  ],
              'yaxis': 'y7'},
             {'marker': {'color': '#D55E00'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.06113813238817719, 0.0629577838412228, 0.08149176775031897,
                    0.0964692447039308, 0.12875636442330052],
              'xaxis': 'x8',
              'y': [contact  , member  , who  , with  , family  ],
              'yaxis': 'y8'},
             {'marker': {'color': '#0072B2'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.06442108916609018, 0.06852516771157065, 0.07230407872254488,
                    0.09424074886793471, 0.09498356340972877],
              'xaxis': 'x9',
              'y': [to  , money  , wealth  , charity  , give  ],
              'yaxis': 'y9'},
             {'marker': {'color': '#CC79A7'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.05636886339948619, 0.06708501164280244, 0.0734468120746225,
                    0.07899992214479891, 0.1664865892159658],
              'xaxis': 'x10',
              'y': [with  , my  , in  , values  , community  ],
              'yaxis': 'y10'},
             {'marker': {'color': '#E69F00'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.04282504778488462, 0.04405121721094704,
                    0.044660688218251136, 0.046097858413150804,
                    0.17143376613990113],
              'xaxis': 'x11',
              'y': [redemption  , is  , something  , guilty  , guilt  ],
              'yaxis': 'y11'},
             {'marker': {'color': '#56B4E9'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.05039870838023675, 0.06012339160165142, 0.06644238273487117,
                    0.08384161474882176, 0.08384161474882176],
              'xaxis': 'x12',
              'y': [have  , reduce  , products  , environment  , environmental  ],
              'yaxis': 'y12'},
             {'marker': {'color': '#009E73'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.05417626527003476, 0.0749319646482701, 0.07664849653673987,
                    0.12496168705943403, 0.13543909743028598],
              'xaxis': 'x13',
              'y': [require  , religion  , does  , self  , control  ],
              'yaxis': 'y13'},
             {'marker': {'color': '#F0E442'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.05786641954426264, 0.058477375921943436,
                    0.06355660801997011, 0.06571289146862001, 0.07322828214747647],
              'xaxis': 'x14',
              'y': [my  , should  , job  , career  , pursue  ],
              'yaxis': 'y14'},
             {'marker': {'color': '#D55E00'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.051958365051832656, 0.05747413523084866,
                    0.06270037035895913, 0.06570509230833711, 0.22865291746915817],
              'xaxis': 'x15',
              'y': [deserves  , with  , my  , an  , addiction  ],
              'yaxis': 'y15'},
             {'marker': {'color': '#0072B2'},
              'orientation': 'h',
              'type': 'bar',
              'x': [0.05816641929831751, 0.06217310110316136, 0.07083329463484148,
                    0.07282459005747068, 0.10447412770189377],
              'xaxis': 'x16',
              'y': [on  , instead  , guilty  , for  , time  ],
              'yaxis': 'y16'}],
    'layout': {'annotations': [{'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 0',
                                'x': 0.0875,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 1',
                                'x': 0.36250000000000004,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 2',
                                'x': 0.6375000000000001,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 3',
                                'x': 0.9125,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 4',
                                'x': 0.0875,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.7250000000000001,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 5',
                                'x': 0.36250000000000004,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.7250000000000001,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 6',
                                'x': 0.6375000000000001,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.7250000000000001,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 7',
                                'x': 0.9125,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.7250000000000001,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 8',
                                'x': 0.0875,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.45,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 9',
                                'x': 0.36250000000000004,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.45,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 10',
                                'x': 0.6375000000000001,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.45,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 11',
                                'x': 0.9125,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.45,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 12',
                                'x': 0.0875,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.175,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 13',
                                'x': 0.36250000000000004,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.175,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 14',
                                'x': 0.6375000000000001,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.175,
                                'yanchor': 'bottom',
                                'yref': 'paper'},
                               {'font': {'size': 16},
                                'showarrow': False,
                                'text': 'Topic 15',
                                'x': 0.9125,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 0.175,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'height': 1000,
               'hoverlabel': {'bgcolor': 'white', 'font': {'family': 'Rockwell', 'size': 16}},
               'showlegend': False,
               'template': '...',
               'title': {'font': {'color': 'Black', 'size': 22},
                         'text': 'Topic Word Scores',
                         'x': 0.5,
                         'xanchor': 'center',
                         'yanchor': 'top'},
               'width': 1000,
               'xaxis': {'anchor': 'y', 'domain': [0.0, 0.175], 'showgrid': True},
               'xaxis10': {'anchor': 'y10', 'domain': [0.275, 0.45], 'showgrid': True},
               'xaxis11': {'anchor': 'y11', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'xaxis12': {'anchor': 'y12', 'domain': [0.825, 1.0], 'showgrid': True},
               'xaxis13': {'anchor': 'y13', 'domain': [0.0, 0.175], 'showgrid': True},
               'xaxis14': {'anchor': 'y14', 'domain': [0.275, 0.45], 'showgrid': True},
               'xaxis15': {'anchor': 'y15', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'xaxis16': {'anchor': 'y16', 'domain': [0.825, 1.0], 'showgrid': True},
               'xaxis2': {'anchor': 'y2', 'domain': [0.275, 0.45], 'showgrid': True},
               'xaxis3': {'anchor': 'y3', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'xaxis4': {'anchor': 'y4', 'domain': [0.825, 1.0], 'showgrid': True},
               'xaxis5': {'anchor': 'y5', 'domain': [0.0, 0.175], 'showgrid': True},
               'xaxis6': {'anchor': 'y6', 'domain': [0.275, 0.45], 'showgrid': True},
               'xaxis7': {'anchor': 'y7', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'xaxis8': {'anchor': 'y8', 'domain': [0.825, 1.0], 'showgrid': True},
               'xaxis9': {'anchor': 'y9', 'domain': [0.0, 0.175], 'showgrid': True},
               'yaxis': {'anchor': 'x', 'domain': [0.825, 1.0], 'showgrid': True},
               'yaxis10': {'anchor': 'x10', 'domain': [0.275, 0.45], 'showgrid': True},
               'yaxis11': {'anchor': 'x11', 'domain': [0.275, 0.45], 'showgrid': True},
               'yaxis12': {'anchor': 'x12', 'domain': [0.275, 0.45], 'showgrid': True},
               'yaxis13': {'anchor': 'x13', 'domain': [0.0, 0.175], 'showgrid': True},
               'yaxis14': {'anchor': 'x14', 'domain': [0.0, 0.175], 'showgrid': True},
               'yaxis15': {'anchor': 'x15', 'domain': [0.0, 0.175], 'showgrid': True},
               'yaxis16': {'anchor': 'x16', 'domain': [0.0, 0.175], 'showgrid': True},
               'yaxis2': {'anchor': 'x2', 'domain': [0.825, 1.0], 'showgrid': True},
               'yaxis3': {'anchor': 'x3', 'domain': [0.825, 1.0], 'showgrid': True},
               'yaxis4': {'anchor': 'x4', 'domain': [0.825, 1.0], 'showgrid': True},
               'yaxis5': {'anchor': 'x5', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'yaxis6': {'anchor': 'x6', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'yaxis7': {'anchor': 'x7', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'yaxis8': {'anchor': 'x8', 'domain': [0.55, 0.7250000000000001], 'showgrid': True},
               'yaxis9': {'anchor': 'x9', 'domain': [0.275, 0.45], 'showgrid': True}}
})

In [21]:
df_sentences.loc[df_sentences["Topics"] == 2, "Question"]

55     Can I morally justify "ghosting" someone if I ...
183    When does compromise become a betrayal of my p...
215    Is it wrong to feel relieved when a difficult ...
473    Is it wrong to find meaning in relationships i...
493    Is it morally okay to leave a relationship tha...
                             ...
787    Is it ethical to enter a new romantic relation...
789    Is it wrong to end a long-term relationship pr...
790    Can an open relationship ever be truly equal, ...
791    Is it morally acceptable to remain in a relati...
792    How do I handle a situation where my partner a...
Name: Question, Length: 63, dtype: str